# Generated by Django 5.2.8 on 2026-07-13 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_teacher_password_plain'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherHomework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=100)),
                ('school_class', models.CharField(max_length=50)),
                ('section', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='teacher_homework/')),
                ('due_date', models.DateField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_homeworks', to='teacher.teacher')),
            ],
            options={
                'verbose_name_plural': 'Teacher Homework Uploads',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
