# Generated by Django 5.2.8 on 2026-05-31 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_remembered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='reminder_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
