# Generated by Django 6.0.4 on 2026-05-25 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='is_remembered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='expense',
            name='reminder_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feepayment',
            name='is_remembered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='feepayment',
            name='reminder_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feetype',
            name='is_remembered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='feetype',
            name='reminder_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
