# Generated by Django 6.0.4 on 2026-06-20 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_document_holiday_attendancelog_directmessage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='password_plain',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Current Password'),
        ),
    ]
