# Generated by Django 6.0.4 on 2026-05-25 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='examschedule',
            name='is_remembered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='examschedule',
            name='reminder_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grade',
            name='is_remembered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='grade',
            name='reminder_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentresult',
            name='is_remembered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentresult',
            name='reminder_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
