# Generated by Django 5.2.8 on 2026-07-16 04:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_syllabus_group_classroutine'),
        ('exams', '0001_initial'),
        ('teacher', '0003_teacherhomework'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='created_by_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_exams', to='teacher.teacher'),
        ),
        migrations.AddField(
            model_name='exam',
            name='exam_type',
            field=models.CharField(choices=[('Class Test', 'Class Test'), ('Half-Yearly', 'Half-Yearly'), ('Annual', 'Annual')], default='Class Test', max_length=20),
        ),
        migrations.AddField(
            model_name='exam',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='examschedule',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='examschedule',
            name='instructions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='examschedule',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academics.section'),
        ),
        migrations.AddField(
            model_name='examschedule',
            name='total_marks',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='examschedule',
            name='room_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
