# Generated by Django 5.2.8 on 2026-05-12 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='attachment',
            field=models.FileField(blank=True, help_text='Upload official PDF or Image notice.', null=True, upload_to='notices/attachments/'),
        ),
        migrations.AddField(
            model_name='notice',
            name='signature',
            field=models.ImageField(blank=True, help_text="Upload headmaster's signature image.", null=True, upload_to='notices/signatures/'),
        ),
    ]
