# Generated by Django 6.0.4 on 2026-06-20 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='password_plain',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Current Password'),
        ),
    ]
