# Generated by Django 5.2.8 on 2026-06-13 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_alter_attendance_options_and_more'),
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studenthomework',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studenthomework',
            name='graded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studenthomework',
            name='marks',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='studenthomework',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_homeworks', to='teacher.teacher'),
        ),
    ]
