# Generated by Django 6.0.4 on 2026-05-23 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='is_remembered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='timetable',
            name='reminder_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
