# Generated by Django 5.2.8 on 2026-06-03 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schoolclass',
            options={'verbose_name_plural': 'School Classes'},
        ),
        migrations.AlterModelOptions(
            name='syllabus',
            options={'verbose_name_plural': 'Syllabuses'},
        ),
    ]
