# Generated by Django 6.0.4 on 2026-06-04 03:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_alter_schoolclass_options_alter_syllabus_options'),
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('topic', models.CharField(blank=True, max_length=255, null=True)),
                ('start_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('Live', 'Live'), ('Scheduled', 'Scheduled'), ('Recorded', 'Recorded')], default='Scheduled', max_length=20)),
                ('meeting_link', models.URLField(blank=True, null=True)),
                ('recording_url', models.URLField(blank=True, null=True)),
                ('duration_minutes', models.IntegerField(default=45)),
                ('students_count', models.IntegerField(default=0)),
                ('school_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='online_classes', to='academics.schoolclass')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='online_classes', to='teacher.teacher')),
            ],
        ),
    ]
