# Generated by Django 6.0.4 on 2026-05-23 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_timetable_is_remembered_timetable_reminder_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='syllabus',
            name='is_remembered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='syllabus',
            name='reminder_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
