# Generated by Django 5.2.8 on 2026-05-26 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_syllabus_is_remembered_syllabus_reminder_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='is_remembered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subject',
            name='reminder_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
