# Generated by Django 5.2.8 on 2026-06-24 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_onlineclass'),
    ]

    operations = [
        migrations.AddField(
            model_name='syllabus',
            name='group',
            field=models.CharField(choices=[('Science', 'Science'), ('Commerce', 'Commerce'), ('Humanities', 'Humanities'), ('General', 'General')], default='General', help_text='The curriculum group this syllabus belongs to.', max_length=20),
        ),
        migrations.CreateModel(
            name='ClassRoutine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Class Routine', max_length=200)),
                ('file', models.FileField(help_text='Upload the routine file (PDF, image, etc.)', upload_to='routines/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routines', to='academics.schoolclass')),
            ],
            options={
                'verbose_name_plural': 'Class Routines',
                'ordering': ['school_class__name'],
            },
        ),
    ]
